_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 55
                - 63
            "2":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 55
                - 63
            "3":
                - 13
                - 16
                - 23
                - 24
                - 55
            "4": 3.8.20
            "5": 0.19.8
            "8":
                - 1
                - 5
            "12": 0.19.8
            "13": darwin-x86_64
backbone:
    value: resnet
batch_size:
    value: 128
center:
    value: mean
dataset:
    value: CIFAR-FS
drop:
    value: 0
feat_size:
    value: 640
gpu:
    value: 0
lr:
    value: 0.0001
max_epoch:
    value: 50
mode:
    value: clip
model_path:
    value: /Users/jdieguez/Documents/master/TFM/code/checkpoints/ResNet-CIFAR-FS.pth
num_workers:
    value: 8
path_to_checkpoints:
    value: /Users/jdieguez/Documents/master/TFM/code/checkpoints
path_to_cifarfs:
    value: /Users/jdieguez/Documents/master/TFM/code/cifar-fs/
path_to_fc100:
    value: /path/to/your/fc100/
path_to_miniimagenet:
    value: /path/to/your/miniimagenet
path_to_tieredimagenet:
    value: /path/to/your/tiredimagenet
project:
    value: SemFew_recreate
query:
    value: 15
run_name:
    value: local
seed:
    value: 13
semantic_size:
    value: 512
shot:
    value: 1
step_size:
    value: 30
test-batch:
    value: 600
test_batch:
    value: 600
test_way:
    value: 5
text_type:
    value: gpt
